### ISSUE TITLE
你好，我pod install下载不来啊，你是不是少上传文件了，请检查看看，谢谢。

### ISSUE THREAD

**Issue by Charles2016** [YK-Unit/SnapshotKit#1]
我下载下来了工程也跑不起来呢，麻烦修复一下，谢谢分享。

**Comment by YK-Unit** [comment]
你好，经过检查确认，工程可以正常运行，不存在少上传文件的情况。

为了能解决你的问题，请参考下面的规则来检测你的操作的正确性：
- 检测是否`Example`这个文件目录下执行`pod install`
- 检测`pod install`执行是否有异常。若执行有异常，请提供对应的log

**Comment by Charles2016** [comment]
额，不好意思，我这边没有在那个Example这个文件目录下执行pod install，现在在这个目录下执行后可以正常运行了，谢谢。
