### ISSUE TITLE
PDF打印出来的图片存在的问题

### ISSUE THREAD

**Issue by lishuailibertine** [YK-Unit/SnapshotKit#2]
你好,请教下,打印出来的图片底部与实际页面底部视觉出现偏差这个有办法优化吗?

**Comment by YK-Unit** [comment]
不好意思，这个问题我暂时也还没找到方法解决。

**Comment by lishuailibertine** [comment]
首先很感谢啊,我看了你分享的文章中提出的三种方案, 后两种都存在少许的问题, 综合比较了下,我还是用了最后PDF转换这种方案,起码不会出现fix元素截取的问题; 我 再想想能不能优化吧😊

**Comment by YK-Unit** [comment]
不客气。如果有找到对应解决方法，非常欢迎提PR~😄
