### ISSUE TITLE
今天更新 Xcode10.2 报错

### ISSUE THREAD

**Issue by loveuqian** [YK-Unit/SnapshotKit#3]
不支持 swift3.0 
swift language version 要改成 swift 4

![image](https://user-images.githubusercontent.com/9745332/54977603-d2391f80-4fd8-11e9-8316-6dae742e08a1.png)

**Comment by YK-Unit** [comment]
好的，感谢反馈。

**Comment by YK-Unit** [comment]
经过测试，Xcode10.2打开Example工程（`SnapshotKit.xcworkspace`），`Swift Language Version`默认是`Swift 4`。

**Comment by YK-Unit** [comment]
鉴于Xcode质量的日益下降，若Xcode10.2打开Example工程（`SnapshotKit.xcworkspace`）后，`Swift Language Version`是`Swift 3`，请手动修改为`Swift 4`。
