### ISSUE TITLE
跟 UIWebView 有关的麻烦删一下，审核被拒了

### ISSUE THREAD

**Issue by pikacode** [YK-Unit/SnapshotKit#4]

**Comment by YK-Unit** [comment]
你好，建议你fork一个分支到个人仓库，然后进行相关裁剪（比如移出掉你认为影响了审核的相关API），以满足你个人的定制需要。

**Comment by pikacode** [comment]
这个不是我的个人定制需求哦，只要是包含 UIWebView 新提交的 App 就在机审不通过

**Comment by YK-Unit** [comment]
感谢反馈，我注意到这个了，稍后会进行处理。

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by YK-Unit** [comment]
[SnapshotKit-v0.3.0](https://github.com/YK-Unit/SnapshotKit/tree/0.3.0) is released for ITMS-90809 now.
